package Model;

public enum RequestStatus {
    REQUEST_APPROVED, REQUEST_DISAPPROVED, WAITING_FOR_SELLER_RESPONSE, PAYMENT_APPROVED, PAYMENT_DISAPPROVED, BUYER_CONFIRMED_PAYMENT,
    TRADE_REQUEST_SENT , TRADE_REQUEST_APPROVED, TRADE_REQUEST_DISAPPROVED;
}
